#!/usr/bin/env python3
"""
Simple test to show Monday Morning Summary message format using mock data.
"""

from datetime import datetime

def create_mock_summary_data():
    """Create mock summary data similar to what the backend would return."""
    return {
        "summary": """📊 **Portfolio Health Overview**

Your PMO portfolio contains 18 active programs with the following status distribution:
- **On Track**: 12 programs (67%)
- **At Risk**: 4 programs (22%) 
- **Off Track**: 2 programs (11%)

🚨 **Programs Requiring Attention**
- *Cloud Migration Initiative*: Delayed infrastructure provisioning, now 3 weeks behind schedule
- *Customer Analytics Platform*: Resource allocation issues impacting Q2 delivery
- *Supply Chain Optimization*: Vendor integration challenges requiring escalation

📅 **Upcoming Key Milestones (Next 7 Days)**
- *Mobile Banking App*: Security review completion (Feb 7)
- *HR System Modernization*: User acceptance testing kickoff (Feb 8)
- *E-commerce Platform Redesign*: Performance testing milestone (Feb 9)

💡 **Strategic Progress Highlights**
- Digital Transformation pipeline shows 85% on-time delivery rate
- Risk mitigation strategies successfully reduced high-severity risks by 40% this quarter
- Cross-functional collaboration improved with 6 programs now sharing technical resources

📈 **Resource Allocation Insights**
- Engineering resources optimally utilized across all programs
- 3 programs identified for additional budget allocation in next planning cycle
- Vendor performance scores averaging 4.2/5.0 across active partnerships""",
        "generated_at": datetime.now().isoformat(),
        "confidence": "high"
    }

def format_summary_for_slack(summary_data):
    """Format portfolio summary for Slack message."""
    summary = summary_data.get("summary", "No summary available")
    confidence = summary_data.get("confidence", "unknown")
    timestamp = summary_data.get("generated_at", datetime.now().isoformat())
    
    # Format timestamp
    try:
        dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
        formatted_time = dt.strftime("%B %d, %Y at %I:%M %p")
    except:
        formatted_time = timestamp
    
    # Build Slack message
    message = f"""🌅 *Good Morning! Here's your PMO Portfolio Summary for {formatted_time}*

{summary}

---
*Confidence Level: {confidence}* | *Generated by PMO AI Assistant* 🤖"""
    
    return message

def main():
    print("🧪 Monday Morning Summary Message Preview")
    print("=" * 60)
    
    # Create mock data
    mock_data = create_mock_summary_data()
    
    # Format for Slack
    slack_message = format_summary_for_slack(mock_data)
    
    print(slack_message)
    print("=" * 60)
    
    print(f"\n📊 Message Stats:")
    print(f"   Length: {len(slack_message)} characters")
    print(f"   Confidence: {mock_data['confidence']}")
    print(f"   Scheduled: Every Monday at 9:00 AM")
    
    print(f"\n📋 This is exactly what will appear in your Slack channel!")
    print(f"   - Professional formatting with emojis")
    print(f"   - Comprehensive portfolio insights")
    print(f"   - Actionable items and upcoming milestones")
    print(f"   - Confidence level indicator")

if __name__ == "__main__":
    main()
