#!/usr/bin/env python3
"""
Test script to generate Monday Morning Summary message without posting to Slack.
This helps us preview what the message will look like before scheduling.
"""

import os
import sys
import json
from datetime import datetime
from pathlib import Path

# Add backend to path so we can import the query handler
backend_path = Path(__file__).parent.parent / "backend"
sys.path.insert(0, str(backend_path))

from agent.query_handler import generate_portfolio_summary


def _format_summary_for_slack(summary_data: dict) -> str:
    """
    Format portfolio summary for Slack message.
    This is copied from the notifications handler to test formatting.
    """
    try:
        summary = summary_data.get("summary", "No summary available")
        confidence = summary_data.get("confidence", "unknown")
        timestamp = summary_data.get("generated_at", datetime.now().isoformat())
        
        # Format timestamp
        try:
            dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
            formatted_time = dt.strftime("%B %d, %Y at %I:%M %p")
        except:
            formatted_time = timestamp
        
        # Build Slack message
        message = f"""🌅 *Good Morning! Here's your PMO Portfolio Summary for {formatted_time}*

{summary}

---
*Confidence Level: {confidence}* | *Generated by PMO AI Assistant* 🤖"""
        
        # Truncate if too long for Slack (4000 char limit)
        if len(message) > 3900:
            message = message[:3870] + "...\n\n*(Summary truncated for length)*"
        
        return message
        
    except Exception as e:
        print(f"Error formatting summary for Slack: {e}")
        return "❌ Error formatting portfolio summary"


def test_summary_generation():
    """Test the Monday Morning Summary generation."""
    print("🧪 Testing Monday Morning Summary Generation...")
    print("=" * 60)
    
    try:
        # Generate summary using the same function the Slack bot uses
        print("1. Calling backend summary function...")
        result = generate_portfolio_summary()
        
        # Format the same way the Slack bot would
        print("2. Formatting for Slack...")
        summary_data = {
            "summary": result.answer,
            "generated_at": datetime.now().isoformat(),
            "confidence": result.confidence
        }
        
        slack_message = _format_summary_for_slack(summary_data)
        
        print("3. Generated Message:")
        print("=" * 60)
        print(slack_message)
        print("=" * 60)
        
        # Show metadata
        print(f"\n📊 Message Stats:")
        print(f"   Length: {len(slack_message)} characters")
        print(f"   Confidence: {result.confidence}")
        print(f"   Sources: {len(result.sources)} sources referenced")
        
        if result.sources:
            print(f"\n📚 Sources Referenced:")
            for i, source in enumerate(result.sources[:5], 1):
                print(f"   {i}. {source.title} ({source.type})")
            if len(result.sources) > 5:
                print(f"   ... and {len(result.sources) - 5} more")
        
        return slack_message
        
    except Exception as e:
        print(f"❌ Error generating summary: {e}")
        import traceback
        traceback.print_exc()
        return None


if __name__ == "__main__":
    # Check if backend is set up
    env_file = Path(__file__).parent.parent / ".env"
    if not env_file.exists():
        print("⚠️  Warning: .env file not found. Make sure backend environment is configured.")
        print("   Required: LLM_PROVIDER, ANTHROPIC_API_KEY or OPENAI_API_KEY")
    
    print("🚀 Starting Monday Morning Summary Test...\n")
    
    message = test_summary_generation()
    
    if message:
        print(f"\n✅ Test completed successfully!")
        print(f"📝 This message will be posted to Slack every Monday at 9:00 AM")
    else:
        print(f"\n❌ Test failed. Check backend configuration and try again.")
